version: '3'

services:
    asimapp-node:
        build: '.'
        ports: 
            - "80:5000"
        environment:
            - NODE_ENV=production
            - MONGO_USER_NAME=debdut_8583
            - MONGO_PASS=Debdut858391
            - SECRET_KEY_ENCRYPT=gfj63543ncbb84846hnfyjfntd786464jfhfn
            - JWT_SECRET=gethnneflknefvhfhr288334njnnf884njnvf8384jidn
            - VIDEO_ACCESS=iamthesupermanu
            - VIDEO_API_KEY=KQ8pkHnSkTOxkz4SJDxJpsWxHPmCMdNtBHrf8jGspYo8QvGk0BLcW2SNIA8OeAsS
        restart: unless-stopped
        

