version: '3'

services: 
    nginx:
        image: nginx:1.15-alpine
        restart: unless-stopped
        ports:
          - "80:80"
          - "443:443"
        depends_on: 
            - asimapp-node
        volumes:
          - ./data/nginx:/etc/nginx/conf.d
          - ./data/nginx/configuration/nginx.conf:/etc/nginx/nginx.conf
          - ./data/nginx/configuration/redirect.conf:/etc/nginx/conf.d/redirect.conf
          - ./data/certbot/conf:/etc/letsencrypt
          - ./data/certbot/www:/var/www/certbot
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    asimapp-node:
        build: '.'
        ports: 
            - "5000:5000"
        environment:
            - NODE_ENV=production
            - MONGO_USER_NAME=debdut_8583
            - MONGO_PASS=Debdut858391
            - SECRET_KEY_ENCRYPT=gfj63543ncbb84846hnfyjfntd786464jfhfn
            - JWT_SECRET=gethnneflknefvhfhr288334njnnf884njnvf8384jidn
            - VIDEO_ACCESS=iamthesupermanu
            - VIDEO_API_KEY=KQ8pkHnSkTOxkz4SJDxJpsWxHPmCMdNtBHrf8jGspYo8QvGk0BLcW2SNIA8OeAsS
        restart: unless-stopped
        

